grafana:
  enabled: false

prometheus:
  enabled: false

loki:
  enabled: true
  auth_enabled: false
  service:
    type: ClusterIP
  config:
    server:
      http_listen_port: 3100
    common:
      path_prefix: /var/loki
      ring:
        kvstore:
          store: inmemory
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    ruler:
      enable_api: true
      rule_path: /tmp/loki/rules
      alertmanager_url: http://mon-kube-prometheus-stack-alertmanager.monitoring:9093
      storage:
        type: local
        local:
          directory: /var/loki/rules

promtail:
  enabled: true
  config:
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /var/log/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_container_name]
            target_label: container
          - action: replace
            replacement: /var/log/pods/*/*/*.log
            target_label: __path__
